version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      production-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "prettier"
          - "eslint*"
        update-types:
          - minor
          - patch
      dev-deps:
        patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "prettier"
          - "eslint*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
      - dependencies

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: monthly
    labels:
      - docker
      - dependencies
